In [16]:
import pandapower.networks as pn
from pandas import DataFrame
import pandapower as pp #import pandapower
import pandapower.topology as top
import networkx as nx
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
net = pn.create_cigre_network_mv(with_der="pv_wind")
net

This pandapower network includes the following parameter tables:
   - bus (15 elements)
   - load (18 elements)
   - sgen (9 elements)
   - switch (8 elements)
   - ext_grid (1 element)
   - line (15 elements)
   - trafo (2 elements)
   - bus_geodata (15 elements)

In [3]:
net.bus

      name  vn_kv type      zone  in_service
0    Bus 0  110.0    b  CIGRE_MV        True
1    Bus 1   20.0    b  CIGRE_MV        True
2    Bus 2   20.0    b  CIGRE_MV        True
3    Bus 3   20.0    b  CIGRE_MV        True
4    Bus 4   20.0    b  CIGRE_MV        True
5    Bus 5   20.0    b  CIGRE_MV        True
6    Bus 6   20.0    b  CIGRE_MV        True
7    Bus 7   20.0    b  CIGRE_MV        True
8    Bus 8   20.0    b  CIGRE_MV        True
9    Bus 9   20.0    b  CIGRE_MV        True
10  Bus 10   20.0    b  CIGRE_MV        True
11  Bus 11   20.0    b  CIGRE_MV        True
12  Bus 12   20.0    b  CIGRE_MV        True
13  Bus 13   20.0    b  CIGRE_MV        True
14  Bus 14   20.0    b  CIGRE_MV        True

In [4]:
net.line.c_nf_per_km = 0

In [5]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,0,0.0,0.195,1.0,1,ol,True

In [6]:
net.line.iat[12, 13]=False 
net.line.iat[13, 13]=False 
net.line.iat[14, 13]=False 
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,0,0.0,0.145,1.0,1,cs,False
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,0,0.0,0.145,1.0,1,cs,False
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,0,0.0,0.195,1.0,1,ol,False

In [7]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line 1-2,CABLE_CIGRE_MV,1,2,2.82,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
1,Line 2-3,CABLE_CIGRE_MV,2,3,4.42,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
2,Line 3-4,CABLE_CIGRE_MV,3,4,0.61,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
3,Line 4-5,CABLE_CIGRE_MV,4,5,0.56,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
4,Line 5-6,CABLE_CIGRE_MV,5,6,1.54,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
5,Line 7-8,CABLE_CIGRE_MV,7,8,1.67,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
6,Line 8-9,CABLE_CIGRE_MV,8,9,0.32,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
7,Line 9-10,CABLE_CIGRE_MV,9,10,0.77,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
8,Line 10-11,CABLE_CIGRE_MV,10,11,0.33,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
9,Line 3-8,CABLE_CIGRE_MV,3,8,1.30,0.501,0.716,0,0.0,0.145,1.0,1,cs,True
10,Line 12-13,OHL_CIGRE_MV,12,13,4.89,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
11,Line 13-14,OHL_CIGRE_MV,13,14,2.99,0.510,0.366,0,0.0,0.195,1.0,1,ol,True
12,Line 6-7,CABLE_CIGRE_MV,6,7,0.24,0.501,0.716,0,0.0,0.145,1.0,1,cs,False
13,Line 11-4,CABLE_CIGRE_MV,11,4,0.49,0.501,0.716,0,0.0,0.145,1.0,1,cs,False
14,Line 14-8,OHL_CIGRE_MV,14,8,2.00,0.510,0.366,0,0.0,0.195,1.0,1,ol,False

In [8]:
pp.runpp(net)

In [9]:
net.res_line

,p_from_mw,q_from_mvar,p_to_mw,q_to_mvar,pl_mw,ql_mvar,i_from_ka,i_to_ka,i_ka,vm_from_pu,va_from_degree,vm_to_pu,va_to_degree,loading_percent
0,2.712214,1.578099,-2.676926,-1.527667,0.035288,0.050432,0.091245,0.091245,0.091245,0.992750,-6.054334,0.975111,-6.534751,62.927781
1,2.676926,1.527667,-2.621616,-1.448622,0.055310,0.079046,0.091245,0.091245,0.091245,0.975111,-6.534751,0.947608,-7.323632,62.927781
2,1.631492,0.433998,-1.629067,-0.430532,0.002425,0.003466,0.051430,0.051430,0.051430,0.947608,-7.323632,0.945793,-7.416319,35.468624
3,1.217417,0.322351,-1.216173,-0.320573,0.001244,0.001777,0.038439,0.038439,0.038439,0.945793,-7.416319,0.944549,-7.480085,26.509314
4,0.518673,0.138245,-0.518050,-0.137354,0.000623,0.000890,0.016405,0.016405,0.016405,0.944549,-7.480085,0.943088,-7.554897,11.313926
5,1.423500,-0.047410,-1.418776,0.054162,0.004724,0.006751,0.043383,0.043383,0.043383,0.947736,-7.036742,0.944755,-7.315386,29.919343
6,1.368705,0.602149,-1.367701,-0.600714,0.001004,0.001435,0.045690,0.045690,0.045690,0.944755,-7.315386,0.943810,-7.350255,31.510242
7,0.823951,0.245136,-0.823151,-0.243992,0.000800,0.001143,0.026293,0.026293,0.026293,0.943810,-7.350255,0.942610,-7.408168,18.133230
8,0.319851,0.082728,-0.319800,-0.082656,0.000051,0.000073,0.010118,0.010118,0.010118,0.942610,-7.408168,0.942418,-7.418149,6.977792
9,0.508425,0.805741,-0.506779,-0.803389,0.001646,0.002352,0.029024,0.029024,0.029024,0.947608,-7.323632,0.944755,-7.315386,20.016477
10,0.578013,0.281628,-0.575436,-0.279779,0.002577,0.001849,0.018559,0.018559,0.018559,1.000084,-5.487407,0.995221,-5.535207,9.517666
11,0.541436,0.258707,-0.540050,-0.257713,0.001386,0.000995,0.017406,0.017406,0.017406,0.995221,-5.535207,0.992436,-5.563923,8.925983
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.943088,-7.554897,NaN,NaN,NaN
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.942418,-7.418149,NaN,NaN,NaN
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.992436,-5.563923,NaN,NaN,NaN

In [10]:
net.res_bus

       vm_pu  va_degree       p_mw     q_mvar
0   1.030000   0.000000 -43.203467 -16.008198
1   0.992750  -6.054334  19.839000   4.637136
2   0.975111  -6.534751   0.000000   0.000000
3   0.947608  -7.323632   0.481700   0.208882
4   0.945793  -7.416319   0.411650   0.108182
5   0.944549  -7.480085   0.697500   0.182329
6   0.943088  -7.554897   0.518050   0.137354
7   0.947736  -7.036742  -1.423500   0.047410
8   0.944755  -7.315386   0.556850   0.147078
9   0.943810  -7.350255   0.543750   0.355578
10  0.942610  -7.408168   0.503300   0.161264
11  0.942418  -7.418149   0.319800   0.082656
12  1.000084  -5.487407  20.010000   4.693341
13  0.995221  -5.535207   0.034000   0.021071
14  0.992436  -5.563923   0.540050   0.257713

In [11]:
net.sgen

    name  bus  p_mw  q_mvar  sn_mva  scaling  in_service type  current_source
0   PV 3    3  0.02     0.0    0.02      1.0        True   PV            True
1   PV 4    4  0.02     0.0    0.02      1.0        True   PV            True
2   PV 5    5  0.03     0.0    0.03      1.0        True   PV            True
3   PV 6    6  0.03     0.0    0.03      1.0        True   PV            True
4   PV 8    8  0.03     0.0    0.03      1.0        True   PV            True
5   PV 9    9  0.03     0.0    0.03      1.0        True   PV            True
6  PV 10   10  0.04     0.0    0.04      1.0        True   PV            True
7  PV 11   11  0.01     0.0    0.01      1.0        True   PV            True
8  WKA 7    7  1.50     0.0    1.50      1.0        True   WP            True

In [14]:
net.load

,name,bus,p_mw,q_mvar,const_z_percent,const_i_percent,sn_mva,scaling,in_service,type
0,Load R1,1,14.99400,3.044662,0.0,0.0,15.300,1.0,True,None
1,Load R3,3,0.27645,0.069285,0.0,0.0,0.285,1.0,True,None
2,Load R4,4,0.43165,0.108182,0.0,0.0,0.445,1.0,True,None
3,Load R5,5,0.72750,0.182329,0.0,0.0,0.750,1.0,True,None
4,Load R6,6,0.54805,0.137354,0.0,0.0,0.565,1.0,True,None
5,Load R8,8,0.58685,0.147078,0.0,0.0,0.605,1.0,True,None
6,Load R10,10,0.47530,0.119121,0.0,0.0,0.490,1.0,True,None
7,Load R11,11,0.32980,0.082656,0.0,0.0,0.340,1.0,True,None
8,Load R12,12,14.99400,3.044662,0.0,0.0,15.300,1.0,True,None
9,Load R14,14,0.20855,0.052268,0.0,0.0,0.215,1.0,True,None
10,Load CI1,1,4.84500,1.592474,0.0,0.0,5.100,1.0,True,None
11,Load CI3,3,0.22525,0.139597,0.0,0.0,0.265,1.0,True,None
12,Load CI7,7,0.07650,0.047410,0.0,0.0,0.090,1.0,True,None
13,Load CI9,9,0.57375,0.355578,0.0,0.0,0.675,1.0,True,None
14,Load CI10,10,0.06800,0.042143,0.0,0.0,0.080,1.0,True,None
15,Load CI12,12,5.01600,1.648679,0.0,0.0,5.280,1.0,True,None
16,Load CI13,13,0.03400,0.021071,0.0,0.0,0.040,1.0,True,None
17,Load CI14,14,0.33150,0.205445,0.0,0.0,0.390,1.0,True,None

In [12]:
#net.res_bus.to_csv(r'C:\Users\LEEPS\Desktop\Python\Energies_Paper\busData.csv', index = None, header=True)

In [21]:
BranchData = DataFrame(net.res_line, columns= ['p_to_mw','q_to_mvar'])
BranchData

     p_to_mw  q_to_mvar
0  -2.676926  -1.527667
1  -2.621616  -1.448622
2  -1.629067  -0.430532
3  -1.216173  -0.320573
4  -0.518050  -0.137354
5  -1.418776   0.054162
6  -1.367701  -0.600714
7  -0.823151  -0.243992
8  -0.319800  -0.082656
9  -0.506779  -0.803389
10 -0.575436  -0.279779
11 -0.540050  -0.257713
12  0.000000   0.000000
13  0.000000   0.000000
14  0.000000   0.000000